
services:
  blue-app:
    image: ghcr.io/ImanolCE/pwa-blue:latest
    container_name: blue-app
    restart: unless-stopped
    ports:
      - "8081:80"

  green-app:
    image: ghcr.io/ImanolCE/pwa-green:latest
    container_name: green-app
    restart: unless-stopped
    ports:
      - "8082:80"
