name: Build and Push Blue/Green Images to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "api/**"
      - "docker/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.js"
    
      - "jest.config.cjs"
  workflow_dispatch:

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    env:
      # IMPORTANTE: todo en min√∫sculas
      OWNER: imanolce
      IMAGE_BLUE: ghcr.io/imanolce/pwa-blue:latest
      IMAGE_GREEN: ghcr.io/imanolce/pwa-green:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run integration tests (Supertest)
        run: npm test -- --runInBand

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ env.OWNER }}" --password-stdin

      - name: Build and push BLUE image
        run: |
          docker build \
            -t "$IMAGE_BLUE" \
            -f docker/blue/Dockerfile .
          docker push "$IMAGE_BLUE"

      - name: Build and push GREEN image
        run: |
          docker build \
            -t "$IMAGE_GREEN" \
            -f docker/green/Dockerfile .
          docker push "$IMAGE_GREEN"
