name: Build and Push Blue/Green Images to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME_BLUE: ghcr.io/${{ github.repository_owner }}/pwa-blue
      IMAGE_NAME_GREEN: ghcr.io/${{ github.repository_owner }}/pwa-green

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run integration tests (Supertest)
        run: npm test

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push BLUE image
        run: |
          docker build \
            -f docker/blue/Dockerfile \
            -t "$IMAGE_NAME_BLUE:latest" \
            .
          docker push "$IMAGE_NAME_BLUE:latest"

      - name: Build and push GREEN image
        run: |
          docker build \
            -f docker/green/Dockerfile \
            -t "$IMAGE_NAME_GREEN:latest" \
            .
          docker push "$IMAGE_NAME_GREEN:latest"
