name: Build and Push Blue/Green Images to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "api/**"
      - "docker/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.js"
      - "jest.config.cjs"
  workflow_dispatch:

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    env:
      OWNER: imanolce
      IMAGE_BLUE: ghcr.io/imanolce/pwa-blue:latest
      IMAGE_GREEN: ghcr.io/imanolce/pwa-green:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run integration tests (Supertest)
        run: npm test -- --runInBand

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push BLUE image
        run: |
          docker build \
            -f docker/blue/Dockerfile \
            -t $IMAGE_BLUE \
            .
          docker push $IMAGE_BLUE

      - name: Build and push GREEN image
        run: |
          docker build \
            -f docker/green/Dockerfile \
            -t $IMAGE_GREEN \
            .
          docker push $IMAGE_GREEN
